import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'Login in our Platform': 'Login in our Platform',
          'Email': 'Email',
          'Password': 'Password',
          'The field is required': 'The field is required',
          'Login': 'Login',
          'Login as Guest': 'Login as Guest',
          'have an account': 'have an account',
          "don't have account": "don't have account",
          'Create account': 'Create account',
          'Sign up in our Platform': 'Sign up in our Platform',
          'Edit Profile': 'Edit Profile',
          "Profile": "My Profile",
          "Name": "User Name",
          'First Name': 'First Name',
          'Last Name': 'Last Name',
          'Please Enter The Password': 'Please Enter The Password',
          'Please Enter The Value': 'Please Enter The Value',
          'Please Enter The Email': 'Please Enter The Email',
          'Password is Short': 'Password is Short',
          'Confirm Password': 'Confirm Password',
          'The Passwords do not match': 'The Passwords do not match',
          'Phone Number': 'Phone Number',
          'The code has been sent to you from email':
              'The code has been sent to you from email',
          "Please insert the code that you recived if you don't get the code you cane make to":
              "Please insert the code that you recived if you don't get the code you cane make to",
          'Resend Code': 'Resend Code',
          'Verification from your email': 'Verification from your email',
          'Search': 'Search',
          'Center Name': 'Center Name',
          'Center City': 'Center City',
          'app_title': 'Language Demo',
          'arabic': 'Arabic',
          'english': 'English',
          'language': 'Language',
          'Dark Mode': 'Dark Mode',
          'Setting': 'Setting',
          'About us': 'About us',
          'Log out': 'Log out',
          'Home': 'Home',
          'Centers': 'Centers',
          'My Operation': 'My Operation',
          'Account': 'Account',
          'More details': 'More details',
          'My Booking': 'My Booking',
          'My Rateing': 'My Rateing',
          'My Volunteers': 'My Volunteers',
          'Login to help you': 'Login to help you',
          'in case join our them you will orgnize your event and life':
              'in case join our them you will organize your event and life',
          'Top Rated': 'Top Rated',
          'Free': 'Free',
          'Paid': 'Paid',
          'City': 'City',
          'Damascus': 'Damascus',
          'Rif Damansucs': 'Rif Damansucs',
          "Homs": 'Homs',
          "Aleppo": 'Aleppo',
          "Daraa": 'Daraa',
          "Hama": 'Hama',
          "Latakia": 'Latakia',
          "Trtous": "Trtous",
          'Explore': 'Explore the app',
          'Discover Appointment': 'Discover Appointment',
          'Discover the Volunteer': 'Discover the Volunteer',
          'The Booking Managament': 'The Booking Managament',
          'The concept of reservation used in this platform is to reserve a seat within the center for a period of time one day, and the reservation is for the next day only.':
              'The concept of reservation used in this platform is to reserve a seat within the center for a period of time one day, and the reservation is for the next day only.',
          'Centers that support to booking': 'Centers that support to booking',
          'The Volunteer Managament': 'The Volunteer Managament',
          'The volunteering operations supported by the platform are a set of activities or campaigns launched by the centers available on the platform. Thus, several categories of campaigns fall into, including educational, service, health, etc.':
              'The volunteering operations supported by the platform are a set of activities or campaigns launched by the centers available on the platform. Thus, several categories of campaigns fall into, including educational, service, health, etc.',
          'Centers that support to volunteer':
              'Centers that support to volunteer',
          'About Center': 'About Center',
          'Who us !': 'Who us !',
          'The address': 'The address',
          'Time work': 'Time work',
          'To communication': 'To communication',
          'Details Center': 'Details Center',
          'Image about center': 'Image about center',
          'our jops': 'our jops',
          'Management Appointment': 'Management Appointment',
          'Management Vlounteer': 'Management Vlounteer',
          'Rate Center': 'Rate Center',
          'Send Feedback': 'Send Feedback',
          "Volunteer Campigian": "Volunteer Campigian",
          "Number of supervisors Requirement":
              "Number of supervisors Requirement",
          "Number of Normal Volunteer Requirment":
              "Number of Volunteer(Subscriber) Requirment",
          "Subscriber": "Subscriber",
          "supervisors": "supervisors",
          "Details Volunteer": "Details Volunteer",
          "Activity type": "Activity type",
          "Description": "Description",
          "Current Number of supervisors Requirement":
              "Current Number of supervisors Requirement",
          "Current Number of Normal Volunteer Requirment":
              "Current Number of Normal Volunteer Requirment",
          "Activity times": "Activity times",
          "Start activity": "Start Date activity",
          "End activity": "End Date activity",
          "Time of Campigain": "Time of Campigain",
          "Volunteer as supervisors": "Volunteer as supervisors",
          "Volunteer as Subscriber": "Volunteer as Subscriber",
          "Unexpected error occurred, please try again":
              "Unexpected error occurred, please try again",
          "Try again": "Try again",
          "Select": "Select",
          "Send your opinion to the center": "Send your opinion to the center",
          "Your opinion about the center": "Your opinion about the center",
          "Help the center by providing constructive feedback":
              "Help the center by providing constructive feedback",
          "Enter Feedback": "Enter Feedback",
          "Like": "Like",
          "Comment": "Comment",
          "Share": "Share",
          "Add_Comment": "Add Comment on this post",
          "Confirm_Booking": "booking confirmation",
          "UnConfirm_Booking": "Unconfirming the booking",
          "An appointment will be booked at this center for tomorrow only":
              "An appointment will be booked at this center for tomorrow only",
          "Confirm_Delete_Booking": "booking delete confirmation",
          "UnConfirm_Delete_Booking": "back",
          "If a previous reservation is available in this center, it will be deleted, if possible":
              "If a previous reservation is available in this center, it will be deleted, if possible",
          "Error": "Error",
          "Add Appointment": "Add Appointment",
          "Delete Appointment": "Delete Appointment",
          "first_name": "First Name",
          "last_name": "Last Name",
          "phone_number": "Phone Number",
          "Undergraduate degree": "Undergraduate degree",
          "Years of Experience": "Years of Experience",
          "Date of Birth": "Date of Birth",
          "Select file": "Select File",
          "Show Appointment": "Show My Booking",
          "First Name person": "First Name person",
          "Last Name booking": "Last Name booking",
          "Date appointment": "Date appointment",
          "My Appointments": "My Appointments",
          "The address center": "The address center",
          "Start time": "Start time",
          "End time": "End time",
          "Not founded any Post": "Not founded any Post",
          "Managment Appointments": "Managment Appointments",
          "Please Enter File": "Please Enter File",
          "Date volunteer": "Date Volunteer Camaign",
          "time volunteer": "Times Volunteer work",
          "to": "to",
          "My Volunteer": "My Volunteer",
          "First Name person v": "First Name person",
          "Date join to pratform": "Date join to platform",
          "Notifications": "Notifications",
          "Number of Notifications": "Number of Notification",
          'Do you want to exit the application?':
              'Do you want to exit the application?',
          "yes": "yes",
          "no": "no",
          "Campaign Name": "Campaign Name",
          "Notification sender": "Notification sender",
          "There are no campaigns announced yet":
              "There are no campaigns announced yet",
          "Volunteer as Subscribe": "Volunteer as Subscribe",
          "Please upload a file containing all the documents required in the campaign conditions":
              "Please upload a file containing all the documents required in the campaign conditions",
          "Volunteer confirmation": "Volunteer confirmation",
          "Please Login before": "Please Login before",
          "Please enter a valid email": "Please enter a valid email",
          "Notification date": "Notification date",
          "No Centers avilable": "No Centers avilable",
          "Please Enter The Phone number": "Please Enter The Phone number",
          "Invalid email address": "Invalid email address",
          "supervisors earnings from the campaign":
              "supervisors earnings from the campaign",
          "Cost to subscribe": "Cost to subscribe",
          "It is a profitable platform that collects centers and enables the user to enjoy the features available for each center within specific conditions and rules.":
              "It is a profitable platform that collects centers and enables the user to enjoy the features available for each center within specific conditions and rules.",
          "What is TOGETHER Platform": "What is TOGETHER Platform",
          "What is Feature in Platform": "What is Feature in Platform",
          "There are many features, the most important of which are: 1- Reservation 2- volunteer 3- feedbacks 4- Submit a complaint 5- The existence of a notification system 6- View and interact with the centers' Posts And many other features":
              "There are many features, the most important of which are: 1- Reservation 2- volunteer 3- feedbacks 4- Submit a complaint 5- The existence of a notification system 6- View and interact with the centers' Posts And many other features",
          "How to book within the platform": "How to book within the platform",
          "desc booking":
              "The reservation system used in the platform is daily, i.e. the user selects the center in which he wants to book and then performs the process of adding a pre-reservation according to certain conditions, which is that it is not possible to add and delete a reservation within the day for more than once, taking into account the capacity of the center.",
          "What is the meaning of volunteering within the center?":
              "What is the meaning of volunteering within the center?",
          "desc volunteer":
              "Volunteering within the centers is divided into two main types: Volunteering as a supervisor. Here you need to fill in all the requirements completely and accurately, because the information entered will be reviewed by the management of the absolute center of the campaign. As for the second type, volunteering as a participant in the campaign, and here you need to upload a file that contains all the documents required in the conditions of the campaign, noting that if the campaign is paid, then you need to confirm the volunteering within the center within 24 hours.",
          "User's Guide": "User's Guide",
          "How to Use This App?": "How to Use This App?",
          "desc use":
              "The application is built to serve the user and build a link between him and all centers, so that the application supports the Arabic and English languages, in addition to the dark mode of the application",
          "Sorry, You can't add more once booking.":
              "Sorry, You can't add more once booking.",
          "Sorry, You can't add appointment, becuase you many cancelled booking.":
              "Sorry, You can't add appointment, becuase you many cancelled booking.",
          "occurred during the add booking process":
              "occurred during the add booking process",
          "you added booking for tomorrow.": "you added booking for tomorrow.",
          "The password is invalid.": "The password is invalid.",
          "occurred during the login process":
              "occurred during the login process",
          "The email is invalid.": "The email is invalid.",
          "The email is already Found.": "The email is already Found.",
          "Succses": "Succses",
          "The Feedback is Send.": "The Feedback is Send.",
          "Please Login before rateing operation":
              "Please Login before rateing operation",
          "You can't join campaign this campaign due you already joined in!":
              "You can't join campaign this campaign due you already joined in!",
          "the volunteer as student is done.":
              "the volunteer as student is done.",
          "the volunteer as subscribe operation is fauiler.":
              "the volunteer as subscribe operation is fauiler.",
          "the volunteer as supervisor is done.":
              "your request is send to cnter it's will review your info",
          "the volunteer as supervisor operation is fauiler.":
              "the volunteer as supervisor operation is fauiler.",
          "no founded any booking": "no founded any booking",
          "no founded any volunteer": "no founded any volunteer",
          "No Post avilable": "No Post avilable",
          "No Notification yet": "No Notification yet",
          "this filed is must be more three letter":
              "this filed is must be more three letter",
          "Date Rate": "Date Rate",
          "rank": "totlal rank",
          "You have a previous evaluation Rateing":
              "You have a previous evaluation Rateing",
          "sorry you can't rating because you haven't any operation in this center.":
              "sorry you can't rating because you haven't any operation in this center.",
          "no founded any rate": "no founded any rate",
          "Sorry, You can't add booking beacuase the center is closed to tomorrow.":
              "Sorry, You can't add booking beacuase the center is closed to tomorrow.",
          "Sorry, You can't add booking beacuase the center is bloked you.":
              "Sorry, You can't add booking beacuase the center is bloked you.",
          "You can't join campaign beacuase your is blocked from this center":
              "You can't join campaign beacuase your is blocked from this center",
          "Please enter an email address": "Please enter an email address",
        },
        'ar': {
          'Login in our Platform': 'تسجيل الدخول في المنصة',
          'Email': 'البريد الالكتروني',
          'Password': 'كلمة السر',
          'The field is required': 'هذا الحقل مطلوب',
          'Login': 'تسجيل الدخول',
          'Login as Guest': 'تسجيل الدخول كزائر',
          'have an account': 'لديك حساب مسبق',
          "don't have account": "ليس لديك حساب",
          'Create account': 'إنشاء حساب',
          'Sign up in our Platform': 'إنشاء حساب في المنصة',
          'Edit Profile': 'تعديل معلومات الحساب',
          'First Name': 'الاسم الأول',
          'Last Name': 'الاسم الاخير',
          'Please Enter The Password': 'الرجاء إدخال كلمة السر',
          'Please Enter The Value': 'الرجاء إدخال قيمة',
          'Please Enter The Email': 'الرجاء إدخال البريد الالكتروني',
          'Password is Short': 'كلمة السر قصيرة',
          'Confirm Password': 'تأكيد كلمة المرور',
          'The Passwords do not match': 'كلمة السر غير متطابقة',
          'Phone Number': 'رقم الموبايل',
          'The code has been sent to you from email':
              'لقد تم إرسال رمز على البريد الالكتروني الخاص بك',
          "Please insert the code that you recived if you don't get the code you cane make to":
              "الرجاء قم بإدخال الرمز الذي تم ارسالها الى البريد الالكتروني الخاص بك , في حال لم يتم الاستلام يمكنك الطلب مجددا",
          'Resend Code': ' إرسال الرمز مجددا',
          'Verification from your email': 'التحقق من بريدك الإلكتروني',
          'Search': 'البحث',
          'Center Name': 'اسم المركز',
          'Center City': 'المدينة',
          'app_title': 'تطبيق اللغة',
          'arabic': 'عربي',
          'english': 'إنجليزي',
          'language': 'لفة التطبيق',
          'Dark Mode': 'وضع التطبيق',
          'Setting': 'الاعدادات',
          'About us': 'حول التطبيق',
          'Log out': 'تسجيل الخروج',
          'Home': 'الرئيسية',
          'Centers': 'المراكز',
          'My Operation': 'خدماتي',
          'Account': 'حسابي',
          'More details': 'مزيد من التفاصيل',
          'My Booking': 'الحجوزات المسبقة',
          'My Rateing': ' التقيمات المسبقة',
          'My Volunteers': 'التطوعات المسبقة',
          'Login to help you': 'انضم إلينا لمزيد من التنظيم والمساعدة',
          'in case join our them you will orgnize your event and life':
              'في حالة الانضمام إلينا ، ستنظم مناسبتك و مواعيدك',
          'Top Rated': 'الأعلى تقييم',
          'Free': 'مجاني',
          'Paid': 'مدفوع',
          'City': 'المدينة',
          'Damascus': 'دمشق',
          'Rif Damansucs': 'ريف دمشق',
          "Homs": 'حمص',
          "Aleppo": 'حلب',
          "Daraa": 'درعا',
          "Hama": 'حماة',
          "Latakia": 'الاذقية',
          "Trtous": "طرطوس",
          'Explore': 'استكشف خدمات المنصة',
          'Discover Appointment': 'استكشف المراكز الداعمة للحجوزات',
          'Discover the Volunteer': 'استكشف المراكز الداعمة لتطوع ضمنها',
          'The Booking Managament': "إدارة عمليات الحجوزات",
          'The concept of reservation used in this platform is to reserve a seat within the center for a period of time one day, and the reservation is for the next day only.':
              'إن مفهوم الحجز المتبع في هذه المنصة هو عبارة عن حجز مقعد ضمن المركز لمدة زمنية يوم واحد ويكون الحجز لليوم التالي فقط.',
          'Centers that support to booking': 'المراكز الداعمة لحجز المسبق',
          'The Volunteer Managament': 'إدارة عمليات التطوع',
          'The volunteering operations supported by the platform are a set of activities or campaigns launched by the centers available on the platform. Thus, several categories of campaigns fall into, including educational, service, health, etc.':
              'إن عمليات التطوع التي تدعمها المنصة هي عبارة عن مجموع من النشاطات أو الحملات التي تطلقها المراكز المتوفرة في المنصة وبالتالي يندرج عدة فئات للحملات منها التعليمية  و الخدمية والصحية الى اخره',
          'Centers that support to volunteer':
              'المراكز التي تدعم عمليات التطوع',
          'About Center': 'حول المركز',
          'Who us !': 'من نحن',
          'The address': 'عنوان المركز',
          'Time work': 'أوقات العمل',
          'To communication': 'لتواصل مع المركز',
          'Details Center': 'تفاصيل المركز',
          'Image about center': 'صور حول المركز',
          'our jops': 'خدماتنا',
          'Management Appointment': 'إدارة عملية الحجز',
          'Management Vlounteer': 'إدارة عمليات التطوع',
          'Rate Center': 'تقيم المركز',
          'Send Feedback': 'إرسال رأيك إلى المركز ',
          "Volunteer Campigian": "الحملات التطوعية",
          "Number of supervisors Requirement": "عدد المشرفين المطلوب",
          "Number of Normal Volunteer Requirment":
              "عدد المتطوعين (المشتركين) المطلوبين",
          "Subscriber": "المشتركين",
          "supervisors": "المشرفين",
          "Details Volunteer": "تفاصيل النشاط",
          "Activity type": "نوع النشاط",
          "Description": "الوصف",
          "Current Number of supervisors Requirement": "عدد المشرفين الحالي",
          "Current Number of Normal Volunteer Requirment":
              "عدد المتطوعين (المشتركين) الحالي",
          "Activity times": "أوقات النشاط",
          "Start activity": "تاريخ بداية النشاط",
          "End activity": "تاريخ نهاية النشاط",
          "Time of Campigain": "أوقات دوام النشاط",
          "Volunteer as supervisors": "التطوع كمشرف",
          "Volunteer as Subscriber": "التطوع كمشترك",
          "Unexpected error occurred, please try again":
              "حدث خطأ ما, يرجى إعادة المحاولة",
          "Try again": "إعادة المحاولة",
          "Select": "تحديد",
          "Send your opinion to the center": "ارسل رأيك للمركز",
          "Your opinion about the center": "رأيك حول المركز",
          "Help the center by providing constructive feedback":
              "قم بمساعدة المركز من خلال تقديم رأي بناء",
          "Enter Feedback": "ارسل رأيك",
          "Like": "أعجبني",
          "Comment": "تعليق",
          "Share": "مشاركة",
          "Add_Comment": "اضف تعليق على هذا المنشور",
          "Confirm_Booking": "تأكيد الحجز",
          "UnConfirm_Booking": "التراجع عن الحجز",
          "An appointment will be booked at this center for tomorrow only":
              "سيتم حجز موعد في هذا المركز ليوم غدا فقط",
          "Confirm_Delete_Booking": "تأكيد حذف الحجز",
          "UnConfirm_Delete_Booking": "تراجع",
          "If a previous reservation is available in this center, it will be deleted, if possible":
              "في حال توافر حجز مسبق في هذا المركز سيتم حذفه في حال كان ذلك ممكنا",
          "Error": "خطأ",
          "Add Appointment": "إضافة حجز مسبق",
          "Delete Appointment": "حذف حجز",
          "first_name": "الأسم الأول",
          "last_name": "الأسم الاخير",
          "phone_number": "رقم الهاتف",
          "Undergraduate degree": "الشهادةالعلمية",
          "Years of Experience": "عدد سنوات الخبرة",
          "Date of Birth": "تاريخ الميلاد",
          "Select file": "اختر ملف",
          "Show Appointment": "عرض حجوزاتي المسبقة",
          "First Name person": "اسم الحاجز",
          "Last Name booking": "الكنية",
          "Date appointment": "تاريخ الحجز",
          "My Appointments": "حجوزاتي المسبقة",
          "The address center": "عنوان المركز",
          "Start time": "وقت بداية العمل",
          "End time": "وقت نهاية العمل",
          "Not founded any Post": "لا يوجد أي منشور مسبق",
          "Managment Appointments": "إدارة الحجوزات",
          "Please Enter File": "الرجاء قم بإدخال ملف",
          "Date volunteer": "تاريخ الحملة ",
          "time volunteer": "أوقات دوام الحملة",
          "to": "إلى",
          "My Volunteer": "تطوعاتي السابقة",
          "First Name person v": "اسم المتطوع",
          "Profile": "الملف الشخصي",
          "Name": "اسم المستخدم",
          "Date join to pratform": "تاريخ الانضمام الى المنصة",
          "Notifications": "الاشعارات",
          "Number of Notifications": "رقم الاشعار",
          'Do you want to exit the application?': 'هل تريد الخروج من التطبيق',
          "yes": "نعم",
          "no": "لاء",
          "Campaign Name": "اسم الحملة",
          "Notification sender": "مرسل الإشعار",
          "There are no campaigns announced yet": "لا يوجد حملات معلنة بعد",
          "Volunteer as Subscribe": "تطوع ضمن الحملة كمشترك",
          "Please upload a file containing all the documents required in the campaign conditions":
              "الرجاء قم برفع ملف يحوي جميع الوثائق المطلوبة في شروط الحملة",
          "Volunteer confirmation": "تأكيد التطوع",
          "Please Login before": "الرجاء قم بتسجيل الدخول ",
          "Please enter a valid email": "الرجاء إدخال بريد إلكتروني صحيح",
          "Notification date": "تاريخ الإشعار",
          "No Centers avilable": "لا يوجد مراكز متوفر حاليا",
          "Please Enter The Phone number": "الرجاء إدخال رقم موبايل",
          "Invalid email address": "البريد الالكتروني غير صحيح",
          "supervisors earnings from the campaign": "أرباح المشرفين من الحملة",
          "Cost to subscribe": "رسم الاشتراك",
          "It is a profitable platform that collects centers and enables the user to enjoy the features available for each center within specific conditions and rules.":
              "هي عبارة عن منصة ربحية تقوم بتجميع المراكز وتمكين المستخدم من التمتع بالميزات المتوفرة لكل مركز ضمن شروط وقواعد محددة.",
          "What is TOGETHER Platform": "ما هي منصة TOGETHER",
          "What is Feature in Platform": "ما هي الميزات المتوفرة ضمن المنصة",
          "There are many features, the most important of which are: 1- Reservation 2- volunteer 3- feedbacks 4- Submit a complaint 5- The existence of a notification system 6- View and interact with the centers' Posts And many other features":
              "يوجد العديد من المميزات من أهمها : 1- الحجز 2- التطوع 3- التقييمات 4- تقديم شكوى 5- وجود نظام إشعارات 6- عرض والتفاعل مع المنشورات الخاصة بالمراكز وغيرها من الميزات العديدة",
          "How to book within the platform":
              "كيف يمكن إتمام عملية الحجز في مركز معين",
          "desc booking":
              "إن نظام الحجز المتبع في المنصة هو يومي أي يقوم المتسخدم بتحديد المركز الذي يريد الحجز ضمنه ثم يقوم بعملية إضافة حجز مسبق وذلك وفق شروط معينة وهي عدم إمكانية إضافة وحذف حجز ضمن اليوم لأكثر من مرة واحدة مع مراعاة الطاقة الاستيعابية للمركز.",
          "What is the meaning of volunteering within the center?":
              "ما معنى التطوع ضمن المركز",
          "desc volunteer":
              "إن التطوع ضمن المراكز ينقسم إلى نوعين رئيسين وهم : التطوع كمشرف وهنا أنت بحاجة إلى تعبئة جميع المتطلبات بشكل كامل ودقيق وذلك بسبب أن المعلومات المدخلة سيت مراجعتها من قبل إدارة المركز المطلق للحملة. أما النوع الثاني هو التطوع كمشترك في الحملة وهنا أنت بحاجة رفع ملف يحوي جيمع الوثائق المطلوبة في شروط الحملة، مع ملاحظة إذا كانت الحملة مدفوعة فأنت بحاجة الى تثبيت التطوع ضمن المركز خلال مدة ٢٤ ساعة.",
          "User's Guide": "دليل المستخدم",
          "How to Use This App?": "كيف يمكن استخدام التطبيق",
          "desc use":
              "إن التطبيق مبني لتخديم المستخدم وبناء صلة الوصل ما بينه وبين جميع المراكز، بحيث التطبيق يدعم اللغتين العربي والانكليزي، بالإضافة الى وضع الداكن للتطبيق ",
          "Sorry, You can't add more once booking.":
              "المعذرة لا تستطيع إضافة أكثر من حجز مسبق",
          "Sorry, You can't add appointment, becuase you many cancelled booking.":
              "عذرا, لا تستطيع إضافة وإلغاء حجز أكثر من مرة.",
          "occurred during the add booking process":
              "حدث خطأ أثناء عملية إضافة الحجز",
          "you added booking for tomorrow.": "لقد تم إضافة حجز مسبق بنجاح",
          "The password is invalid.": "كلمة المرور خطأ",
          "occurred during the login process":
              "حدث خطأ أثناء عملية تسجيل الدخول",
          "The email is invalid.": "البريد الالكتروني غير موجود",
          "The email is already Found.": "البريد الالكتروني موجود مسبقا",
          "Succses": "العملية نجحت",
          "The Feedback is Send.": "لقد تم إرسال الى المركز",
          "Please Login before rateing operation":
              "الرجاء تسجيل الدخول قبل إتمام العملية",
          "You can't join campaign this campaign due you already joined in!":
              "انت فعلا منضم للحملة",
          "the volunteer as student is done.":
              "لقد تم إرسال طلبك متطوع مشترك يرجى مراجعة المركز وتثبيت الحجز ضمن مدة 24 ساعة  ",
          "the volunteer as subscribe operation is fauiler.":
              "لقد فشت عملية إرسال ططلب التطوع",
          "the volunteer as supervisor is done.":
              "لقد تم إرسال طلبك سيتم مراجعة المعلومات والتحقق منها يرجى الاطلاع على الإشعارات",
          "the volunteer as supervisor operation is fauiler.":
              "لقد فشلت عملية الانضمام يرجى المعاودة لاحقا",
          "no founded any booking": "لا يوجد حجوزات سابقة",
          "no founded any volunteer": "لا يوجد حملات تم التطوع بها مسبقا",
          "No Post avilable": "لا يوجد منشورات حاليا",
          "No Notification yet": "لا يوجد إشعارات",
          "this filed is must be more three letter":
              "يجب أن يكون المدخلات أكثر من 3 أحرف",
          "Date Rate": "تاريخ التقييم",
          "rank": "مقدار التقييم",
          "You have a previous evaluation Rateing":
              "لقد قمت بتقيم سابق يرجى تقييم المركز في نشاط اخر",
          "sorry you can't rating because you haven't any operation in this center.":
              "المعذرة لا يمكنك التقييم لأنك لم تقم بأي عملية في هذا المركز.",
          "no founded any rate": "لا يوجد مراكز مقيمة مسبقا",
          "Sorry, You can't add booking beacuase the center is closed to tomorrow.":
              "عذرا لايمكن إضافة حجز بسبب إغلاق المركز عن العمل ليوم غد",
          "Sorry, You can't add booking beacuase the center is bloked you.":
              "عذرا لا يمكن إضافة حجز مسبق وذلك بسبب حظرك من إدراة المركز",
          "You can't join campaign beacuase your is blocked from this center":
              "لا يمكنك الانضام لهذه الحملة بسبب حظرك من إدارة المركز",
          "Please enter an email address": "قم بإدخال البريد الالكتروني"
        },
      };
}
