import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          "Purchase and payment can be made through select global payment gateways":
              "Purchase and payment can be made through select global payment gateways",
          "Convenient payment": "Convenient payment",
          "You can purchase and choose the delivery process that suits you":
              "You can purchase and choose the delivery process that suits you",
          "Delivery Capability Goods": "Delivery Capability Goods",
          "Save time and effort by using our system":
              "Save time and effort by using our system",
          "Shorten time and effort": "Shorten time and effort",
          "Login in our platform": "Login in our platform",
          "Email": "Email",
          "Please enter an email address": "Please enter an email address",
          "Invalid email address": "Invalid email address",
          "Password": "Password",
          "Please Enter The Password": "Please Enter The Password",
          "Password is Short": "Password is Short",
          "Login": "Login",
          "Login as Guest": "Login as Guest",
          "Don't have an account": "Don't have an account",
          "Create account": "Create account",
          "Create account in our platform": "Create account in our platform",
          "First Name": "First Name",
          "Last Name": "Last Name",
          "Please enter an First Name": "Please enter an First Name",
          "Please enter an Last Name": "Please enter an Last Name",
          "Confirm Password": "Confirm Password",
          "City": "City",
          "you have account": "you have account",
          "Home": "Home",
          "Cart": "Cart",
          "Favorit": "Favorit",
          "Account": "Account",
          "Search on Product": "Search on Product",
          "Register now easily": "Register now easily",
          "Create a new account and make your life more effective and regular with us":
              "Create a new account and make your life more effective and regular with us",
          "Language": "Language",
          "Russian": "Russian",
          "Arabic": "Arabic",
          "English": "English",
          "Qr Code": "Qr Code",
          "Logout": "Logout",
          "Add to cart": "Add to cart",
          "Price": "Price",
          "Total": "Total",
          "Add to Favorites": "Add to Favorites",
          "Quantity": "Quantity",
          "Buy": "Buy",
          "Add to Cart button pressed in ProductCard":
              "Add to Cart button pressed in ProductCard",
          "the field is required": "the field is required",
          "number of pieces": "number of pieces",
          "Please select the number of products you want":
              "Please select the number of products you want",
          "Not found products": "Not found products",
          "Please Enter The City": "Please Enter The City",
          "you have an account": "you have an account",
          "Phone Number": "Phone Number",
          "Please enter a Phone Number": "Please enter a Phone Number",
          "Get Started": "Get Started",
          "Next": "Next",
          "Last offer": "Last offer",
          "Old price": "Old price",
          "Please select the way to payment":
              "Please select the way to payment",
          "My Requests": "My Orders",
          "Order number": "Order number",
          "order status": "order status",
          "number of products": "number of products",
          "Total price": "total price",
          "delivery status": "delivery status",
          "order date": "order date",
          "QR Code Scanner" : "QR Code Scanner",
          "Delete form cart" : "Delete",
          "Edit" : "Edit",
          "Edit on total" : "Edit on total",
        },
        'ar': {
          "Purchase and payment can be made through select global payment gateways":
              "يمكن الشراء والدفع من خلال بوابات دفع عالمية محددة",
          "Convenient payment": "عمليات الدفع سلسة",
          "You can purchase and choose the delivery process that suits you":
              "يمكنك شراء واختيار عملية التسليم التي تناسبك",
          "Delivery Capability Goods": "بضائع قابلة للتوصيل",
          "Save time and effort by using our system":
              "وفر الوقت والجهد باستخدام نظامنا",
          "Shorten time and effort": "قلل الوقت والجهد",
          "Login in our platform": "تسجيل الدخول في منصتنا",
          "Email": "البريد الإلكتروني",
          "Please enter an email address": "الرجاء إدخال عنوان بريد إلكتروني",
          "Invalid email address": "عنوان بريد إلكتروني غير صالح",
          "Password": "كلمة المرور",
          "Please Enter The Password": "الرجاء إدخال كلمة المرور",
          "Password is Short": "كلمة المرور قصيرة",
          "Login": "تسجيل الدخول",
          "Login as Guest": "تسجيل الدخول كضيف",
          "Don't have an account": "ليس لديك حساب؟",
          "Create account": "إنشاء حساب",
          "Create account in our platform": "إنشاء حساب في منصتنا",
          "First Name": "الاسم الأول",
          "Last Name": "الاسم الأخير",
          "Please enter an First Name": "الرجاء إدخال الاسم الأول",
          "Please enter an Last Name": "الرجاء إدخال الاسم الأخير",
          "Confirm Password": "تأكيد كلمة المرور",
          "City": "المدينة",
          "You have an account": "لديك حساب بالفعل",
          "Home": "الرئيسية",
          "Cart": "عربة التسوق",
          "Favorit": "المفضلة",
          "Account": "الحساب",
          "Search on Product": "البحث عن المنتج",
          "Register now easily": "سجل الآن بسهولة",
          "Create a new account and make your life more effective and regular with us":
              "أنشئ حسابًا جديدًا واجعل حياتك أكثر فعالية وانتظامًا معنا",
          "Language": "اللغة",
          "Russian": "الروسية",
          "Arabic": "العربية",
          "English": "الإنجليزية",
          "Qr Code": "رمز الاستجابة السريعة",
          "Logout": "تسجيل الخروج",
          "Add to cart": "أضف إلى السلة",
          "Price": "السعر",
          "Total": "الإجمالي",
          "Add to Favorites": "اضف الى المفضلة",
          "Quantity": "الكمية",
          "Buy": "شراء",
          "Add to Cart button pressed in ProductCard": "",
          "the field is required": "الحقل مطلوب",
          "number of pieces": "عدد القطع",
          "Please select the number of products you want":
              "يرجى تحديد عدد المنتجات التي تريدها",
          "Not found products": "لم يتم العثور على منتجات",
          "you have an account": "لديك حساب سابق",
          "Phone Number": "رقم الهاتف",
          "Please enter a Phone Number": "الرجاء إدخال رقم الهاتف",
          "Get Started": "ابدأ",
          "Next": "التالي",
          "Last offer": "اخر العروض",
          "Old price": "السعر القديم",
          "Please select the way to payment": "الرجاء قم بتحديد طريقة الدفع",
          "My Requests": "طلباتي",
          "Order number": "رقم الطلب",
          "order status": "حالة الطلب",
          "number of products": "عدد المنتجات",
          "Total price": "السعر الاجمالي",
          "delivery status": "حالة التوصيل",
          "order date": "تاريخ الطلب",
          "QR Code Scanner" : "ماسح الكود",
          "Delete form cart" : "حذف"
          ,"Edit" : "تعديل",
          "Edit on total" : "التعديل على الكمية"
        },
        'ru': {
          "Purchase and payment can be made through select global payment gateways":
              "Покупка и оплата могут быть произведены через выбранные мировые платежные шлюзы",
          "Convenient payment": "Удобная оплата",
          "You can purchase and choose the delivery process that suits you":
              "Вы можете приобрести и выбрать процесс доставки, который вам подходит",
          "Delivery Capability Goods": "Товары с возможностью доставки",
          "Save time and effort by using our system":
              "Экономьте время и усилия, используя нашу систему",
          "Shorten time and effort": "Сократите время и усилия",
          "Login in our platform": "Войти на нашу платформу",
          "Email": "Электронная почта",
          "Please enter an email address":
              "Пожалуйста, введите адрес электронной почты",
          "Invalid email address": "Неверный адрес электронной почты",
          "Password": "Пароль",
          "Please Enter The Password": "Введите пароль",
          "Password is Short": "Пароль слишком короткий",
          "Login": "Войти",
          "Login as Guest": "Войти как гость",
          "Don't have an account": "У вас нет аккаунта",
          "Create account": "Создать аккаунт",
          "Create account in our platform":
              "Создать аккаунт на нашей платформе",
          "First Name": "Имя",
          "Last Name": "Фамилия",
          "Please enter an First Name": "Пожалуйста, введите имя",
          "Please enter an Last Name": "Пожалуйста, введите фамилию",
          "Confirm Password": "Подтвердите пароль",
          "City": "Город",
          "you have account": "У вас уже есть аккаунт",
          "Home": "Главная",
          "Cart": "Корзина",
          "Favorit": "Избранное",
          "Account": "Аккаунт",
          "Search on Product": "Поиск по продуктам",
          "Register now easily": "Зарегистрируйтесь легко",
          "Create a new account and make your life more effective and regular with us":
              "Создайте новый аккаунт и сделайте свою жизнь более эффективной и регулярной с нами",
          "Language": "Язык",
          "Russian": "Русский",
          "Arabic": "Арабский",
          "English": "Английский",
          "Qr Code": "QR-код",
          "Logout": "Выйти",
          "Add to cart": "Добавить в корзину",
          "Price": "Цена",
          "Total": "Итого",
          "Add to Favorites": "Добавить в список фаворитов",
          "Quantity": "количество",
          "Buy": "купить",
          "Add to Cart button pressed in ProductCard":
              "Нажатая кнопка Добавить в корзину в ProductCard",
          "the field is required": "the field is required",
          "number of pieces": "количество штук",
          "Please select the number of products you want":
              "Пожалуйста, выберите количество продуктов, которые вы хотите",
          "Not found products": "Не найденные продукты",
          "you have an account": "у вас есть аккаунт",
          "Phone Number": "номер телефона",
          "Please enter a Phone Number": "Пожалуйста, введите номер телефона",
          "Get Started": "начать работу",
          "Next": "следующий",
          "Last offer": "последнее предложение",
          "Old price": "старая цена",
          "Please select the way to payment":
              "Пожалуйста, выберите способ оплаты",
          "My Requests": "мои просьбы",
          "Order number": "номер заказа",
          "order status": "Статус заказа",
          "number of products": "Количество товаров",
          "Total price": "Общая стоимость",
          "delivery status": "Статус доставки",
          "order date": "Дата заказа",
          "QR Code Scanner" : "сканер QR-кодов",
          "Delete form cart" : "Удалять",
          "Edit" : "редактировать"
          ,"Edit on total" : "Изменять итого"
        },
      };
}
